repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3.12
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.279
    hooks:
      - id: ruff
        args: ["--fix"]
        additional_dependencies: []
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.26.0
    hooks:
      - id: semgrep
        args: ["--config", ".semgrep/pre-commit-rules.yml"]
        files: "\\.py$"
  - repo: local
    hooks:
      - id: check-python-shebang
        name: check-python-shebang
        entry: python -m scripts.validate_shebangs
        language: system
        files: "\\.py$"
        stages: [commit]