name: CI - JustNewsAgent Tests

# Run on manual dispatch and pull requests to main/dev branches
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  test:
    name: Run tests (conda environment)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ShellCheck shell scripts
        run: |
          echo "Installing shellcheck and running it against shell scripts"
          sudo apt-get update -y
          sudo apt-get install -y shellcheck
          files=$(git ls-files '*.sh' 'scripts/**/*.sh' 'deploy/systemd/**/*.sh' || true)
          if [ -z "$files" ]; then
            echo "No shell scripts found to lint"
          else
            echo "Running shellcheck on: $files"
            shellcheck -x $files
          fi
        # Allow the team to iterate; make this an enforceable check in the future by removing continue-on-error
        continue-on-error: false

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          auto-update-conda: true
          activate-environment: justnews-v2-py312
          environment-file: environment.yml
          use-mamba: true

      - name: Install additional dependencies
        shell: bash -l {0}
        run: |
          # Ensure we're in the activated environment
          conda activate justnews-v2-py312

          # Upgrade pip and install any additional requirements
          pip install -U pip setuptools wheel

          # Install requirements.txt dependencies (if not already covered by environment.yml)
          pip install -r requirements.txt

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          conda activate justnews-v2-py312
          # Run unit tests only (exclude integration tests)
          pytest -v -k "not integration" --tb=short --maxfail=5

      - name: Run startup dry-run check
        shell: bash -l {0}
        run: |
          conda activate justnews-v2-py312
          # Verify the startup wrapper computes a start mode without executing actions
          ./square-one.sh start --dry-run --yes

      - name: Run integration tests (optional)
        shell: bash -l {0}
        run: |
          conda activate justnews-v2-py312
          # Run integration tests if they exist
          pytest -v -k "integration" --tb=short --maxfail=3 || echo "No integration tests found or failed"
        continue-on-error: true

      - name: Generate test coverage report
        shell: bash -l {0}
        run: |
          conda activate justnews-v2-py312
          # Install coverage tools if not present
          pip install pytest-cov coverage

          # Run tests with coverage
          pytest --cov=. --cov-report=xml --cov-report=term -k "not integration"
        continue-on-error: true

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true

  version-compliance:
    name: Version Compliance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run version compliance validation
        run: |
          python scripts/validate_version_compliance.py

      - name: Run version consistency check
        run: |
          python scripts/validate_versions.py
